name: Merge stage to prod at release

on:
  release:
    types: [published]

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: 'Merge'
        id: merge
        uses: imsamdez/actions.merge-branch@v1.0.6
        with:
          base: prod # Change this according to your need
          compare: stage # Change this according to your need
          github_token: ${{ secrets.GITHUB_TOKEN }}
